# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests with Native Coverage
      run: dotnet test --configuration Release --no-restore --coverage --coverage-output-format cobertura

    - name: Install ReportGenerator Tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
          -reports:"**/TestResults/**/*.cobertura.xml" \
          -targetdir:"coveragereport" \
          -reporttypes:"HtmlInline_AzurePipelines;MarkdownSummary"

    - name: Publish Coverage Summary to PR
      if: github.event_name == 'pull_request'
      run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coveragereport/
        retention-days: 7
        
    - name: Set up JDK 17
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Cache SonarQube Cloud packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarQube Cloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ runner.temp }}\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarQube Cloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}/scanner
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: bash
      run: |
        ${{ runner.temp }}/scanner/dotnet-sonarscanner begin /k:"ThomasDixini_YFCore.Backend" /o:"thomasdixini" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        dotnet build
        ${{ runner.temp }}/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
